title: Tayla's Projects
logo: /images/profile.png
theme: jekyll-theme-minimal

Statistics Graduate | Data Analyst Time Series • Regression • Excel • R • Forecasting

Featured Projects 

- Retail Trial Analysis (Excel) 
- Gas Price Forecasting (R) 
- Election Vote Modeling (R)
- Modeling House Prices (R) 
